# 日志
logging:
  config: classpath:log4j2-local.yml
  
# 数据源
spring:
  # mysql数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/job?useUnicode=true&characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    username: root
    password: 123456
    # 连接池配置
    initial-size: ${JOB_DS_INIT_SIZE:1}
    minIdle: ${JOB_DS_MIN_IDLE:5}
    maxActive: ${JOB_DS_MAX_ACTIVE:5}
    maxWait: ${JOB_DS_MAX_WAIT:60000}
    timeBetweenEvictionRunsMillis: ${JOB_DS_TBERM:60000}
    minEvictableIdleTimeMillis: ${JOB_DS_MEITM:300000}
    validation-query: ${JOB_DS_VALIDATE_QUERY:SELECT 1 FROM DUAL}
    test-while-idle: ${JOB_DS_TEST_WHILE_IDLE:true}
    test-on-borrow: ${JOB_DS_TEST_ON_BORROW:false}
    test-on-return: ${JOB_DS_TEST_ON_BORROW:false}
    pool-prepared-statements: ${JOB_DS_POOL_PREPARED_STATEMENTS:true}
    max-pool-prepared-statement-per-connection-size: ${JOB_DS_MPPSPCS:20}
    filters: ${JOB_DS_FILTERS:stat,log4j2}
    connection-properties:
    - key: druid.stat.mergeSql
      value: true
    - key: druid.stat.slowSqlMillis
      value: 5000
  thymeleaf:
    # Enable template caching.
    cache: false
    # Check that the templates location exists.
    check-template-location: true
    servlet:
      content-type: text/html
    # Enable MVC Thymeleaf view resolution.
    enabled: true
    # Template encoding.
    encoding: UTF-8
    # Comma-separated list of view names that should be excluded from resolution.
#      excluded-view-names:
    # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    mode: HTML5
    # Prefix that gets prepended to view names when building a URL.
    prefix: classpath:/templates/
    # Suffix that gets appended to view names when building a URL.
    suffix: .html
    # Order of the template resolver in the chain.
#      template-resolver-order:
#       Comma-separated list of view names that can be resolved.
#      view-names:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/, file:${job.tmp.path}
  http:
    encoding:
      force: true
#添加那个目录的文件需要restart
  devtools:
    restart:
      additional-paths: src/main/java
      enabled: true
#排除那个目录的文件不需要restart
#      exclude: src/main/resources
  redis:
    host: localhost
    port: 6379
    database: 0
  jackson:
    date-format: yyyy-MM-dd HH:mm

#mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zxkj.job.bean.po
  typeEnumsPackage: com.zxkj.job.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

# ~ druid stat
druid:
  init: true
  username: root
  password: 123456
  log-slow-sql: true


# ~ redis
#redis:
#  host-name: ${REDIS_HOST:127.0.0.1}
#  port: ${REDIS_PORT:6379}
#  database: ${REDIS_DATABASE:1}
##  password: ${REDIS_PASSWORD:1234}
#  block-when-exhausted: ${REDIS_BLOCK:true}
#  jmx-enabled: ${REDIS_JMX_ENABLE:true}
#  min-idle: ${REDIS_MIN_IDLE:0}
#  max-total: ${REDIS_MAX_TOTAL:50}
#  max-idle: ${REDIS_MAX_IDLE:10}
#  max-wait-millis: ${REDIS_MAX_WAIT_MILLIS:20000}
#  test-on-borrow: ${REDIS_TEST_ON_BORROW:true}
#  test-on-return: ${REDIS_TEST_ON_RETURN:true}
#  test-while-idle: ${REDIS_TEST_WHILE_IDLE:true}
#  num-tests-per-eviction-run: ${REDIS_TEST_PER_EVICT_RUN:2}
#  time-between-eviction-runs-millis: ${REDIS_BETWEEN_EVICT_MILLIS:15000}

